# Multiple Linear Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

## Encoding categorical data

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
ct = ColumnTransformer(transformers=[('encoder', OrdinalEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [5]:
print(X)

[[2.0 165349.2 136897.8 471784.1]
 [0.0 162597.7 151377.59 443898.53]
 [1.0 153441.51 101145.55 407934.54]
 [2.0 144372.41 118671.85 383199.62]
 [1.0 142107.34 91391.77 366168.42]
 [2.0 131876.9 99814.71 362861.36]
 [0.0 134615.46 147198.87 127716.82]
 [1.0 130298.13 145530.06 323876.68]
 [2.0 120542.52 148718.95 311613.29]
 [0.0 123334.88 108679.17 304981.62]
 [1.0 101913.08 110594.11 229160.95]
 [0.0 100671.96 91790.61 249744.55]
 [1.0 93863.75 127320.38 249839.44]
 [0.0 91992.39 135495.07 252664.93]
 [1.0 119943.24 156547.42 256512.92]
 [2.0 114523.61 122616.84 261776.23]
 [0.0 78013.11 121597.55 264346.06]
 [2.0 94657.16 145077.58 282574.31]
 [1.0 91749.16 114175.79 294919.57]
 [2.0 86419.7 153514.11 0.0]
 [0.0 76253.86 113867.3 298664.47]
 [2.0 78389.47 153773.43 299737.29]
 [1.0 73994.56 122782.75 303319.26]
 [1.0 67532.53 105751.03 304768.73]
 [2.0 77044.01 99281.34 140574.81]
 [0.0 64664.71 139553.16 137962.62]
 [1.0 75328.87 144135.98 134050.07]
 [2.0 72107.6 127864.55 353183.

## Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [7]:
from scipy.stats import wilcoxon
# compare samples
stat, p = wilcoxon(X_train[0], X_test[0])
print('Statistics=%.3f, p=%.3f' % (stat, p))
# interpret
alpha = 0.05
if p > alpha:
	print('Same distribution (fail to reject H0)')
else:
	print('Different distribution (reject H0)')

ValueError: `x` (and `y`, if provided) must be an array of real numbers.

## Training the Multiple Linear Regression model on the Training set

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

## Predicting the Test set results

In [ ]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))